#!/usr/bin/env bash

set -e

rm -rf build/js/
rm -rf build/css/

mkdir -p build/js/
mkdir -p build/css/

browserify -d src/js/index.js -t babelify -t envify | uglifyjs --compress --mangle --source-map content="inline",filename="index.js.map",url="index.js.map" --output build/js/index.js
lessc src/less/index.less build/css/index.css --silent --compress && postcss --use autoprefixer -r build/css/index.css
